dist : trusty
language: java
jdk:
  - oraclejdk8
sudo: required
env:  
  global:
    - MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"
    - MAVEN_OPTS="-Xms1g -Xmx2g" 
  matrix: 
    - SONAR=true
    - SONAR=false RUNSCANNER=true
    - SONAR=false RUNSCANNER=false PLAIN=true
    - SONAR=false RUNSCANNER=false PLAIN=false BULK_TESTS=true
    - SONAR=false RUNSCANNER=false PLAIN=false BULK_TESTS=false

git:
  depth: 3

addons:
    sonarcloud:
        organization: "miso-lims"
        token:
            secure: "CuaZUL0SJiRQR3Z+zvSTKAJc+/SOC+2g5a9gG08NYYSkwN8Ujwoyd9e14DLuyFaY2xZppQb5OIcQWQH+lmZqZbycRuAlBsTy1iIooUFB9v80g5eW8RDaJu3609Y7emSV7sZ3wuTJx3sTDeITAbkhRz0FQ2FyyoFMgD1jI+lxPXA="
        github_token:
            secure: "PsRH/x31KHGk/l0QlwMLDj437bKnWxJF45o2AiYZofVQZRVXzhhhpVxMqMl3QZ25K8wq5Qr7F2a2MYdMHtUpl0RBL5TWMDTmP9T1hyjA8IuqYx8Lq2ZklOvB4HJa/HgZEGVRWDyl4XE3giVDsYxPNogFTD1ieE6rs3XC0KkhQWY="
        branches:
            - develop

before_install:
    - git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
    - cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"
    - 'echo pr slug ${TRAVIS_PULL_REQUEST_SLUG} && echo repo slug ${TRAVIS_REPO_SLUG}'

before_script:
  - export MAVEN_OPTS='-Xms1g -Xmx2g' CXX=g++-5
  - sudo apt-add-repository -y ppa:likemartinma/devel
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y pkg-config cmake libjsoncpp-dev autoconf libtool build-essential gcc-5 g++-5
script:
  
  - 'if ($SONAR); then
        if [[ ${TRAVIS_PULL_REQUEST_SLUG} == ${TRAVIS_REPO_SLUG} ]] ; then 
            mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar ;
        else 
            echo "[WARN] SonarCloud cannot run on pull requests from forks." ; 
        fi
     elif ($RUNSCANNER); then
        pushd runscanner-illumina && ./build-illumina-interop && autoreconf -i && ./configure && make && popd;
        PATH=$PATH:$(pwd)/runscanner-illumina mvn clean -P external -Dmaven.javadoc.skip=true -DskipIllumina=false install;
     elif ($PLAIN); then
        mvn -P external clean verify -DrunPlainITs;
     elif ($BULK_TESTS); then
        mvn -P external clean verify -Dmaven.javadoc.skip=true -DskipITs=false -Dit.test=Bulk*;
     else
        mvn -P external clean verify -Dmaven.javadoc.skip=true -DskipITs=false -Dit.test=!'"Bulk*"';
     fi'


cache:
  directories:
    - "$HOME/.sonar/cache"
    - "$HOME/.m2"

notifications:
  email: false
  slack:
    rooms:
      secure: Op3cFjj8lw8y5I+Bh4Hq0yt4G9Rx2GNOuwo6onjHGRrlODIPvFE0GCD+aEWmB76qcH/Lq/9NRf86Ik2tWnQbBRrwkH7bcJjmK05DvRFP3gvqIMiReHKugdYcthMnI+ep2PX+tiUMt3OwLAT9F2tpmOjEm2oG6DRsJ45oN/iUpVo=
    on_success: change
    on_failure: always

